### ISSUE TITLE
User should see contact information

### ISSUE THREAD

**Issue by gregkorte** [iiimosley/iiimosley.github.io#5]
**Given** a user visits your personal site
**When** the user clicks the *Contact* navigation link
**Then** the user should see at least two links of yours on social media (i.e. Twitter, LinkedIn, etc.)

**Comment by iiimosley** [comment]
contact grid has been created.
users can see 4 forms of contact (email, linkedin, github, twitter) on an animated grid.
when user clicks either the icon or handle div's, a new tab opens for the profile (or, via email, the users email application opens to send a new email directed to my email)
